services:
  # Músico 1: El Baterista (Base de Datos)
  postgres:
    image: postgres:15-alpine
    container_name: nexus-sales-db
    restart: always
    env_file:
      - backend/docker.env.prod
    # NOTA: En producción, no exponemos el puerto de la BD al mundo exterior
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Músico 2: El Guitarrista (Backend)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod  # Optimizado para producción
    container_name: nexus-api
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - backend/.env.production  # Archivo de variables de producción
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production

volumes:
  postgres_data: