ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "productId" TEXT;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
