ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "User" ADD CONSTRAINT "User_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
